version: '3'

services:
  database:
    image: 'mysql:latest'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - 'MYSQL_ROOT_PASSWORD=s3cr3t'
      - 'MYSQL_USER=arithmetics'
      - 'MYSQL_DATABASE=arithmetics'
      - 'MYSQL_PASSWORD=s3cr3t'
      - 'TZ=UTC'

  arithmetics:
    #image: public.ecr.aws/j3c6d5f6/arithmetics:latest ## Uncomment this to pull from AWS ECR and comment out build
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      - 'JDBC_URL=database:3306/arithmetics'
      - 'JDBC_USER=arithmetics'
      - 'JDBC_PASSWORD=s3cr3t'
    ports:
      - '8080:8080'
      - '5005:5005'