arithmetics:
  security:
    jwtSecret: "VGhpcyBpcyBhIHByb2plY3QgdG8gYmUgZXZhbHVhdGVkIGZvciB0aGUgSmF2YSBEZXZlbG9wZXIgcG9zaXRpb24gYXQgVHJ1ZU5vcnRoCg=="
    jwtAccessTokenExpirationInMs: 86400000

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/db-master-changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/arithmetics?allowPublicKeyRetrieval=true&useSSL=false
    username: arithmetics
    password: s3cr3t
    driver-class-name: com.mysql.cj.jdbc.Driver
