spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/arithmetics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: arithmetics
    password: s3cr3t
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    ROOT: INFO
    dev.jlcorradi: DEBUG