arithmetics:
  demo-user:
    email: demouser@jlcorradi.dev
    password: password
    balance: 50
  security:
    jwtSecret: "VGhpcyBpcyBhIHByb2plY3QgdG8gYmUgZXZhbHVhdGVkIGZvciB0aGUgSmF2YSBEZXZlbG9wZXIgcG9zaXRpb24gYXQgVHJ1ZU5vcnRoCg=="
    jwtAccessTokenExpirationInMs: 86400000

randomDotOrg:
  apiUrl: "https://api.random.org"
  apiKey: "25775a38-5c88-42a7-8780-aa5bd9bc8b20"

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/db-master-changelog.xml
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://${JDBC_URL}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    ROOT: ERROR