spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://mysql:3366/arithmetics?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: arithmetics
    password: s3cr3t
    driver-class-name: com.mysql.cj.jdbc.Driver

  docker:
    compose:
      file: classpath:docker/embedded-compose.yml

logging:
  level:
    ROOT: INFO
    dev.jlcorradi: DEBUG