version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3366:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - 'MYSQL_ROOT_PASSWORD=s3cr3t'
      - 'MYSQL_USER=arithmetics'
      - 'MYSQL_DATABASE=arithmetics'
      - 'MYSQL_PASSWORD=s3cr3t'
      - 'TZ=UTC'
